name: Deploy
 
on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /apps/prereg
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_ed25519
            source ~/.profile
            git pull
            nvm use
            npm ci
            npm run build
            pm2 restart prereg